name: Build Geode Mod for Android

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/geode-sdk/build-android:latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake .. -DGEODE_PLATFORM=Android64 -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make package

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: geode-android-mod
          path: build/*.geode
